### ISSUE TITLE
Ledger Nano Invalid status 6d00 after signing

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/electrum-komodo#32]
Tested on windows 10 VM (installation from binary), and Ubuntu 18.04 using dev branch of repo.

Steps to reproduce: Load wallet, go to send tab, enter recipient (tried both send to self and send to other address) and amount (tx would include acrued rewards). After confirming the transation on the Ledger device, a popup appears - 
![image](https://user-images.githubusercontent.com/35845239/73717095-c8815c00-4753-11ea-912d-fc323a25c888.png)

Ledger firmware: 1.6.0
Ledger KMD app version: 1.3.17

Console logs below:
```Traceback (most recent call last):
  File "/home/smk762/electrum-komodo/plugins/ledger/ledger.py", line 433, in sign_transaction
    outputData = self.get_client().finalizeInput(b'', 0, 0, changePath, bfh(rawTx))
  File "/home/smk762/electrum-komodo/plugins/ledger/btchip_zcash.py", line 199, in finalizeInput
    response = self.dongle.exchange(bytearray(apdu))
  File "/home/smk762/.local/lib/python3.6/site-packages/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
btchip.btchipException.BTChipException: Exception : Invalid status 6d00
Traceback (most recent call last):
  File "/home/smk762/electrum-komodo/plugins/ledger/ledger.py", line 433, in sign_transaction
    outputData = self.get_client().finalizeInput(b'', 0, 0, changePath, bfh(rawTx))
  File "/home/smk762/electrum-komodo/plugins/ledger/btchip_zcash.py", line 199, in finalizeInput
    response = self.dongle.exchange(bytearray(apdu))
  File "/home/smk762/.local/lib/python3.6/site-packages/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
btchip.btchipException.BTChipException: Exception : Invalid status 6d00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smk762/electrum-komodo/gui/qt/util.py", line 648, in run
    result = task.task()
  File "/home/smk762/electrum-komodo/lib/wallet.py", line 1452, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/smk762/electrum-komodo/plugins/ledger/ledger.py", line 252, in wrapper
    return func(self, *args, **kwargs)
  File "/home/smk762/electrum-komodo/plugins/ledger/ledger.py", line 501, in sign_transaction
    self.give_error(e, True)
  File "/home/smk762/electrum-komodo/plugins/ledger/ledger.py", line 245, in give_error
    raise Exception(message)
Exception: Exception : Invalid status 6d00
```

**Comment by smk762** [comment]
a second attempt to send MAX funds to external address was successful (previous attempts, amount was < MAX)

**Comment by tonymorony** [comment]
Was able to reproduce (but with MAX amount)
Also it might be helpful: got similar error (`Invalid status 6d00`) when rejected tx broadcasting by ledger

**Comment by tonymorony** [comment]
fixed by https://github.com/KomodoPlatform/electrum-komodo/pull/36
